data_path:
  BTC:
    1min:
      raw: "../Data/crypto-1min/btc-min1/raw_data/"
      cleaned: "../Data/crypto-1min/btc-min1/cleaned_data/"
      neural_LSTM: "../Data/crypto-1min/btc-min1/neural_data_LSTM/"
      neural_transformers: "../Data/crypto-1min/btc-min1/neural_data_transformers/"
  ETH:
    1min:
      raw: "../Data/crypto-1min/eth-min1/raw_data/"
      cleaned: "../Data/crypto-1min/eth-min1/cleaned_data/"
      neural_LSTM: "../Data/crypto-1min/eth-min1/neural_data_LSTM/"
      neural_transformers: "../Data/crypto-1min/eth-min1/neural_data_transformers/"

Strategy:
  LSTM:
    data_path_X: "Data/crypto-1min/eth-min1/neural_data_LSTM/ETH_MACD_march2024_X.pt"
    data_path_y: "Data/crypto-1min/eth-min1/neural_data_LSTM/ETH_MACD_march2024_y.pt"
    weights_path: "io/LSTM/Weights/"
    load_weights: True
    batch_size: 64
    learning_rate: 0.001
    nb_epochs: 200
    hidden_size: 15
    num_layers: 10
    dropout: 0.2
    input_size: 1
  Transformers:
    data_path_X: "Data/crypto-1min/btc-min1/neural_data_transformers/BTC-2021min_X.pt"
    data_path_y: "Data/crypto-1min/btc-min1/neural_data_transformers/BTC-2021min_y.pt"
    weights_path: "io/Transformers/Weights/"
    loss_path: "io/Transformers/Losses/"
    save_path: "io/Transformers/"
    load_weights: True
    batch_size: 512
    learning_rate: 0.001
    nb_epochs: 350
    embedding_size: 8
    kernel_size: 5
    nb_heads: 8
    padding: 2
    nb_encoder_layers: 8
    forward_expansion: 4
    forward_expansion_decoder: 4
    max_len: 5000
    dropout: 0.2
    normalize: False
    debug: False
    debug_name: False
    wandb: False
    dh_params:
      to_load: "BTC"
      window: 10
      look_forward: 1
      log_close: True
      close_returns: False
      only_close: True
