data_path:
  BTC:
    1min:
      raw: "../Data/crypto-1min/btc-min1/raw_data/"
      cleaned: "../Data/crypto-1min/btc-min1/cleaned_data/"
      neural_fc: "../Data/crypto-1min/btc-min1/neural_data_fc/"
      neural_LSTM: "../Data/crypto-1min/btc-min1/neural_data_LSTM/"
      neural_transformers: "../Data/crypto-1min/btc-min1/neural_data_transformers/"
  ETH:
    1min:
      raw: "../Data/crypto-1min/eth-min1/raw_data/"
      cleaned: "../Data/crypto-1min/eth-min1/cleaned_data/"
      neural_fc: "../Data/crypto-1min/eth-min1/neural_data_fc/"
      neural_LSTM: "../Data/crypto-1min/eth-min1/neural_data_LSTM/"
      neural_transformers: "../Data/crypto-1min/eth-min1/neural_data_transformers/"

live_test:
  main:
    strategy: "StrategyFC"
    fc:
      window: 10
      hidden_size: 100
      dropout: 0.2
      device: "cpu"
      weights_path: "../io/FC/2024-04-29_14-50-50/weights/weights.pt"
    lstm:
      window: 10
      hidden_size: 16
      num_layers: 5
      dropout: 0.2
      device: "cpu"
      weights_path: "../io/LSTM/2024-04-24_01-19-18/weights/weights.pt"
    buy_percentage: 0.01
    wallet: 1000

back_test:
  main:
    strategy: "StrategyFC"
    fc:
      window: 10
      hidden_size: 100
      dropout: 0.2
      device: "cpu"
      weights_path: "../io/FC/2024-04-29_14-50-50/weights/weights.pt"
    buy_percentage: 0.01
    wallet: 1000
    data_files: ['Data/crypto-1min/btc-min1/cleaned_data/BTC_april2018.csv',
                'Data/crypto-1min/btc-min1/cleaned_data/BTC_april2019.csv',
                'Data/crypto-1min/btc-min1/cleaned_data/BTC_april2020.csv',
                'Data/crypto-1min/btc-min1/cleaned_data/BTC_april2021.csv',
                'Data/crypto-1min/btc-min1/cleaned_data/BTC_august2018.csv',
                'Data/crypto-1min/btc-min1/cleaned_data/BTC_august2019.csv',
                'Data/crypto-1min/btc-min1/cleaned_data/BTC_august2020.csv',
                'Data/crypto-1min/btc-min1/cleaned_data/BTC_august2021.csv',
                'Data/crypto-1min/btc-min1/cleaned_data/BTC_december2018.csv',
                'Data/crypto-1min/btc-min1/cleaned_data/BTC_december2019.csv',
                'Data/crypto-1min/btc-min1/cleaned_data/BTC_december2021.csv',
                'Data/crypto-1min/btc-min1/cleaned_data/BTC_december2023.csv',
                'Data/crypto-1min/btc-min1/cleaned_data/BTC_february2018.csv',
                'Data/crypto-1min/btc-min1/cleaned_data/BTC_february2019.csv',
                'Data/crypto-1min/btc-min1/cleaned_data/BTC_february2020.csv',
                'Data/crypto-1min/btc-min1/cleaned_data/BTC_february2021.csv',
                'Data/crypto-1min/btc-min1/cleaned_data/BTC_february2022.csv',
                'Data/crypto-1min/btc-min1/cleaned_data/BTC_february2024.csv',
                'Data/crypto-1min/btc-min1/cleaned_data/BTC_january2018.csv',
                'Data/crypto-1min/btc-min1/cleaned_data/BTC_january2019.csv',
                'Data/crypto-1min/btc-min1/cleaned_data/BTC_january2020.csv',
                'Data/crypto-1min/btc-min1/cleaned_data/BTC_january2021.csv',
                'Data/crypto-1min/btc-min1/cleaned_data/BTC_january2022.csv',
                'Data/crypto-1min/btc-min1/cleaned_data/BTC_january2024.csv',
                'Data/crypto-1min/btc-min1/cleaned_data/BTC_july2018.csv',
                'Data/crypto-1min/btc-min1/cleaned_data/BTC_july2019.csv',
                'Data/crypto-1min/btc-min1/cleaned_data/BTC_july2020.csv',
                'Data/crypto-1min/btc-min1/cleaned_data/BTC_july2021.csv',
                'Data/crypto-1min/btc-min1/cleaned_data/BTC_june2018.csv',
                'Data/crypto-1min/btc-min1/cleaned_data/BTC_june2019.csv',
                'Data/crypto-1min/btc-min1/cleaned_data/BTC_june2020.csv',
                'Data/crypto-1min/btc-min1/cleaned_data/BTC_june2021.csv',
                'Data/crypto-1min/btc-min1/cleaned_data/BTC_march2018.csv',
                'Data/crypto-1min/btc-min1/cleaned_data/BTC_march2019.csv',
                'Data/crypto-1min/btc-min1/cleaned_data/BTC_march2020.csv',
                'Data/crypto-1min/btc-min1/cleaned_data/BTC_march2021.csv',
                'Data/crypto-1min/btc-min1/cleaned_data/BTC_march2024.csv',
                'Data/crypto-1min/btc-min1/cleaned_data/BTC_may2018.csv',
                'Data/crypto-1min/btc-min1/cleaned_data/BTC_may2019.csv',
                'Data/crypto-1min/btc-min1/cleaned_data/BTC_may2020.csv',
                'Data/crypto-1min/btc-min1/cleaned_data/BTC_may2021.csv',
                'Data/crypto-1min/btc-min1/cleaned_data/BTC_november2018.csv',
                'Data/crypto-1min/btc-min1/cleaned_data/BTC_november2019.csv',
                'Data/crypto-1min/btc-min1/cleaned_data/BTC_november2020.csv',
                'Data/crypto-1min/btc-min1/cleaned_data/BTC_november2021.csv',
                'Data/crypto-1min/btc-min1/cleaned_data/BTC_october2018.csv',
                'Data/crypto-1min/btc-min1/cleaned_data/BTC_october2019.csv',
                'Data/crypto-1min/btc-min1/cleaned_data/BTC_october2020.csv',
                'Data/crypto-1min/btc-min1/cleaned_data/BTC_october2021.csv',
                'Data/crypto-1min/btc-min1/cleaned_data/BTC_september2018.csv',
                'Data/crypto-1min/btc-min1/cleaned_data/BTC_september2019.csv',
                'Data/crypto-1min/btc-min1/cleaned_data/BTC_september2020.csv',
                'Data/crypto-1min/btc-min1/cleaned_data/BTC_september2021.csv']

Strategy:
  FC:
    data_path_X: "Data/crypto-1min/btc-min1/neural_data_FC/BTC_january2024_X.pt"
    data_path_y: "Data/crypto-1min/btc-min1/neural_data_FC/BTC_january2024_y.pt"
    loss_path: "io/FC/Losses/"
    weights_path: "io/FC/Weights/"
    save_path: "io/FC/"
    load_weights: False
    batch_size: 2048
    learning_rate: 0.001
    nb_epochs: 5000
    hidden_size: 100
    dropout: 0.2
    input_size: 1
    wandb: False
    debug: False
    dh_params:
      window: 10
      look_forward: 1
      log_close: False
      close_returns: False
      only_close: True
      min_max_scaling: False
  LSTM:
    data_path_X: "Data/crypto-1min/btc-min1/neural_data_LSTM/BTC_january2024_X.pt"
    data_path_y: "Data/crypto-1min/btc-min1/neural_data_LSTM/BTC_january2024_y.pt"
    loss_path: "io/LSTM/Losses/"
    weights_path: "io/LSTM/Weights/"
    save_path: "io/LSTM/"
    load_weights: False
    batch_size: 2048
    learning_rate: 0.001
    nb_epochs: 400
    hidden_size: 16
    num_layers: 5
    dropout: 0.2
    input_size: 1
    wandb: True
    debug: False
    dh_params:
      window: 10
      look_forward: 1
      log_close: False
      close_returns: False
      only_close: True
      min_max_scaling: True
  Transformers:
    data_path_X_encoder: "Data/crypto-1min/eth-min1/neural_data_transformers/BTC_january2024_X_encoder.pt"
    data_path_X_decoder: "Data/crypto-1min/eth-min1/neural_data_transformers/BTC_january2024_X_decoder.pt"
    data_path_y: "Data/crypto-1min/eth-min1/neural_data_transformers/ETH_MACD_january2024_y.pt"
    weights_path: "io/Transformers/Weights/"
    loss_path: "io/Transformers/Losses/"
    save_path: "io/Transformers/"
    load_weights: True
    batch_size: 512
    learning_rate: 0.001
    nb_epochs: 150
    embedding_size: 128
    kernel_size: 5
    nb_heads: 8
    padding: 2
    nb_encoder_layers: 12
    forward_expansion: 4
    forward_expansion_decoder: 4
    max_len: 5000
    dropout: 0.2
    normalize: False
    debug: False
    debug_name: False
    wandb: False
    dh_params:
      window: 10
      look_forward: 1
      decoder_horizon: 2
      log_close: False
      close_returns: False
      only_close: True
      min_max_scaling: False
