data_path:
  BTC:
    1min:
      raw: "../Data/crypto-1min/btc-min1/raw_data/"
      cleaned: "../Data/crypto-1min/btc-min1/cleaned_data/"
      neural_fc: "../Data/crypto-1min/btc-min1/neural_data_fc/"
      neural_LSTM: "../Data/crypto-1min/btc-min1/neural_data_LSTM/"
      neural_transformers: "../Data/crypto-1min/btc-min1/neural_data_transformers/"
  ETH:
    1min:
      raw: "../Data/crypto-1min/eth-min1/raw_data/"
      cleaned: "../Data/crypto-1min/eth-min1/cleaned_data/"
      neural_fc: "../Data/crypto-1min/eth-min1/neural_data_fc/"
      neural_LSTM: "../Data/crypto-1min/eth-min1/neural_data_LSTM/"
      neural_transformers: "../Data/crypto-1min/eth-min1/neural_data_transformers/"

Strategy:
  FC:
    data_path_X: "Data/crypto-1min/btc-min1/neural_data_FC/BTC-2021min_X.pt"
    data_path_y: "Data/crypto-1min/btc-min1/neural_data_FC/BTC-2021min_y.pt"
    loss_path: "io/FC/Losses/"
    weights_path: "io/FC/Weights/"
    save_path: "io/FC/"
    load_weights: True
    batch_size: 2048
    learning_rate: 0.001
    nb_epochs: 5000
    hidden_size: 100
    dropout: 0.2
    input_size: 1
    wandb: False
    debug: False
    dh_params:
      window: 10
      look_forward: 1
      log_close: False
      close_returns: False
      only_close: True
      min_max_scaling: False
  LSTM:
    data_path_X: "Data/crypto-1min/eth-min1/neural_data_LSTM/ETH_MACD_january2024_X.pt"
    data_path_y: "Data/crypto-1min/eth-min1/neural_data_LSTM/ETH_MACD_january2024_y.pt"
    loss_path: "io/LSTM/Losses/"
    weights_path: "io/LSTM/Weights/"
    save_path: "io/LSTM/"
    load_weights: False
    batch_size: 2048
    learning_rate: 0.001
    nb_epochs: 2000
    hidden_size: 128
    num_layers: 25
    dropout: 0.2
    input_size: 1
    wandb: False
    debug: False
    dh_params:
      window: 10
      look_forward: 1
      log_close: False
      close_returns: False
      only_close: True
      min_max_scaling: True
  Transformers:
    data_path_X_encoder: "Data/crypto-1min/eth-min1/neural_data_transformers/ETH_MACD_january2024_X_encoder.pt"
    data_path_X_decoder: "Data/crypto-1min/eth-min1/neural_data_transformers/ETH_MACD_january2024_X_decoder.pt"
    data_path_y: "Data/crypto-1min/eth-min1/neural_data_transformers/ETH_MACD_january2024_y.pt"
    weights_path: "io/Transformers/Weights/"
    loss_path: "io/Transformers/Losses/"
    save_path: "io/Transformers/"
    load_weights: True
    batch_size: 512
    learning_rate: 0.001
    nb_epochs: 150
    embedding_size: 128
    kernel_size: 5
    nb_heads: 8
    padding: 2
    nb_encoder_layers: 12
    forward_expansion: 4
    forward_expansion_decoder: 4
    max_len: 5000
    dropout: 0.2
    normalize: False
    debug: False
    debug_name: False
    wandb: False
    dh_params:
      window: 10
      look_forward: 1
      decoder_horizon: 2
      log_close: False
      close_returns: False
      only_close: True
      min_max_scaling: False
